In [17]:
import numpy as np

In [18]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [- 1.5 , 2.7 , 3.3 , - 0.8]]
weights = [[0.2, 0.8, -0.5, 1],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]
weights3 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]
biases3 = [-1, 2, -0.5]

In [19]:
print(f"inputs: {np.shape(inputs)}")
print(f"weights: {np.shape(weights)}")
print(f"weights2: {np.shape(weights2)}")

inputs: (3, 4)
weights: (3, 4)
weights2: (3, 3)


In [20]:
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
print(f"layer1_outputs: {np.shape(layer1_outputs)}")

layer1_outputs: (3, 3)


In [21]:
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

In [22]:
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [23]:
layer3_outputs = np.dot(layer2_outputs, np.array(weights3).T) + biases3

In [24]:
layer4_outputs = np.dot(layer3_outputs, np.array(weights3).T) + biases3
print(layer4_outputs)

[[-2.11222927  3.58871827  2.13664196]
 [-2.7573264   4.76311959  3.78986432]
 [-1.03001389  2.73693985  2.04939577]]
