In [1]:
import numpy as np
import nnfs

In [2]:
nnfs.init()

In [3]:
n_inputs = 2
n_neurons = 4

In [4]:
weights = 0.01 * np.random.randn(n_inputs, n_neurons)
biases = np.zeros((1, n_neurons))

In [5]:
print(weights)
print(biases)

[[ 0.01764052  0.00400157  0.00978738  0.02240893]
 [ 0.01867558 -0.00977278  0.00950088 -0.00151357]]
[[0. 0. 0. 0.]]


In [20]:
np.random.randn()

1.0370473699550113