In [4]:
import numpy as np

test_no = 0

def testIt(xArray, yArray):
    global test_no
    test_no +=1
    print(f"Test: {test_no:02d}")
    print(f"  Shape x: {xArray.shape}")
    print(f"  Shape y: {yArray.shape}")
    r = np.dot(xArray, yArray)
    print(f"  Result Type: {type(r)}")
    print(f"  Result Value: {r}")

In [5]:
x = [1,2,3]
y = [[1],[2],[3]]
xArray = np.array(x)
yArray = np.array(y)

testIt(xArray, yArray)

Test: 01
  Shape x: (3,)
  Shape y: (3, 1)
  Result Type: <class 'numpy.ndarray'>
  Result Value: [14]


In [6]:
x = [1, 2, 3]
y = [1, 2, 3]
xArray = np.array([x])
yArray = np.array([y]) 

testIt(xArray, yArray)

Test: 02
  Shape x: (1, 3)
  Shape y: (1, 3)


ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [7]:
x = [1,2,3]
y = [[1,2,3],[1,2,3],[1,2,3]]
xArray = np.array(x)
yArray = np.array(y)

testIt(xArray, yArray)

Test: 03
  Shape x: (3,)
  Shape y: (3, 3)
  Result Type: <class 'numpy.ndarray'>
  Result Value: [ 6 12 18]


In [8]:
x = [[1,2,3]]
y = [[1,2,3],[1,2,3],[1,2,3]]
xArray = np.array(x)
yArray = np.array(y)

testIt(xArray, yArray)

Test: 04
  Shape x: (1, 3)
  Shape y: (3, 3)
  Result Type: <class 'numpy.ndarray'>
  Result Value: [[ 6 12 18]]


In [10]:
x = [[1,2,3],[1,2,3],[1,2,3],[1,2,3]]
y = [[1,2,3],[1,2,3],[1,2,3]]
xArray = np.array(x)
yArray = np.array(y)

testIt(xArray, yArray)

Test: 06
  Shape x: (4, 3)
  Shape y: (3, 3)
  Result Type: <class 'numpy.ndarray'>
  Result Value: [[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]
